### ISSUE TITLE
Problem loading the dataset

### ISSUE THREAD

**Issue by vatsal2473** [iiitl/tweet_classification#2]
The dataset format was updated and now there is a problem loading the dataset in the both the notebooks
* Premise_classification_RoBERTa_baseline.ipynb
*  Stance_detection_RoBERTa_baseline.ipynb
- [x] fix this bug in code cell 4 and 7 of both the notebooks

**Comment by parth-verma7** [comment]
Hi @vatsal2473 I would like to work on this issue, can you please assign it to me?

**Comment by gokullan** [comment]
Hi @vatsal2473. Has the dataset format changed from tsv to csv? If so, please assign this issue to me. I will update the code

**Comment by vatsal2473** [comment]
> Hi @vatsal2473. Has the dataset format changed from tsv to csv? If so, please assign this issue to me. I will update the code

Yes, the dataset format has changed
